<template>
  <div class="game-page">
    <NavigationHeader 
      class="navigation"
      v-model:search-term="searchTerm"
      @search="onSearch"
      :loading="searchLoading"
    />

    <!-- Loading State -->
     <div v-if="loading" class="loading-spinner">
      <Spinner message="Searching for game reports..." />
    </div>

    <!-- Error State -->
    <ErrorMessage :message="error" @dismiss="clearError" class="error-with-top-margin" />

    <!-- Game ready State -->
     <div v-if="game && !pendingGame && !loading && !error">
      <GameDescription :game="game" />
      <AskAICard 
        class="settings-section" 
        :title="`What is the community saying?`"
        :animate-text="true"
        :content="aiCardContent"
        :type-speed="15"
        :start-delay="800"
        @feedback="(feedback) => {
          submitGameSummaryVote(game.game_id, feedback)
        }"
      >
      </AskAICard>
      <GameReportsSection v-if="game.reports" :reports="game.reports" />
      <AddReport :game-id="gameId" />
    </div>
    <!-- Processing State -->
    <div v-else-if="!loading && !error">
      <ProcessingWarning :game-name="gameTitle" />
      <div class="refresh-button-container">
        <RefreshButton :countdown-start="60" />
      </div>
      <RandomArt />
    </div>
  </div>
</template>

<script>
import Spinner from '../components/base/Spinner.vue'
import AskAICard from '../components/common/AskAICard.vue'
import ErrorMessage from '../components/common/ErrorMessage.vue'
import RandomArt from '../components/common/RandomArt.vue'
import RefreshButton from '../components/common/RefreshButton.vue'
import AddReport from '../components/ui/AddReport.vue'
import GameDescription from '../components/ui/GameDescription.vue'
import GameReportsSection from '../components/ui/GameReportsSection.vue'
import ProcessingWarning from '../components/ui/ProcessingWarning.vue'
import apiService from '../services/backend/apiService.js'
import { sortGameReportsPerRelevance } from '../helpers/report.helper.js'
import NavigationHeader from '../components/ui/NavigationHeader.vue'

export default {
  name: 'GamePage',
  components: {
    AddReport,
    GameDescription,
    GameReportsSection,
    ProcessingWarning,
    ErrorMessage,
    Spinner,
    RefreshButton,
    RandomArt,
    AskAICard,
    NavigationHeader,
  },
  props: {
    gameId: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      game: null,
      loading: false,
      error: null,
      searchPerformed: false,
      processingWarning: false,
      searchLoading: false,
      searchTerm: '',
    }
  },
  computed: {
    gameTitle() {
      return this.game?.steam_app?.name || `Game ID ${this.gameId}`
    },
    aiCardContent() {
      if (!this.game?.game_performance_summary) return ''

      const summary = this.game.game_performance_summary
      const disclaimer =
        '\n\n<i>This is a brief summary of community feedback generated by AI and may contain errors.\nPlease refer to the community reports for accurate information.</i>'

      return summary + disclaimer
    },
  },
  watch: {
    gameId: {
      immediate: true,
      handler() {
        this.loadGame()
      },
    },
  },
  async mounted() {
    // Add keyboard event listener for backspace key
    document.addEventListener('keydown', this.handleKeydown)
    this.updateDocumentTitle()
    this.loadGame()
  },
  unmounted() {
    // Remove keyboard event listener to prevent memory leaks
    document.removeEventListener('keydown', this.handleKeydown)
  },
  methods: {
    handleKeydown(event) {
      // Check if backspace key is pressed and not in an input field
      if (event.key === 'Backspace' && !this.isInInputField(event.target)) {
        event.preventDefault()
        this.$router.back()
      }
    },

    onSearch() {
      if (!this.searchTerm) return
      this.searchLoading = true
      // redirect to search results page with delay
      setTimeout(() => {
        this.searchLoading = false
        this.$router.push({ name: 'SearchResults', query: { q: this.searchTerm } })
      }, 300)
    },

    isInInputField(target) {
      // Check if the target element is an input field where backspace should work normally
      const inputTypes = ['INPUT', 'TEXTAREA', 'SELECT']
      return inputTypes.includes(target.tagName) || target.contentEditable === 'true'
    },

    clearError() {
      this.error = null
    },

    updateDocumentTitle() {
      document.title = `${this.gameTitle} - Steam Deck Settings DB`
    },

    async loadGame() {
      if (!this.gameId) {
        this.error = 'Unknown game ID.'
        return
      }

      this.loading = true
      this.error = null
      this.game = null
      this.searchPerformed = true
      this.pendingGame = false

      try {
        const res = await apiService.fetchGame(this.gameId)

        if (res.status === 'queued') {
          this.pendingGame = true
          this.game = res.game
          return
        }

        const sortedReports = sortGameReportsPerRelevance(res.game.reports)
        this.game = { ...res.game, reports: sortedReports }
      } catch (err) {
        this.error = err.message
      } finally {
        this.loading = false
      }
    },
    submitGameSummaryVote(gameId, feedback) {
      const voteType = feedback === 'positive' ? 'up' : feedback === 'negative' ? 'down' : null
      if (!voteType) return
      return apiService.submitGameSummaryVote(gameId, voteType)
    },
  },
}
</script>

<style scoped>
.game-page {
  width: 100%;
}

.navigation {
  margin-bottom: 40px;
}

.settings-section {
  margin-top: 20px;
}

.error-with-top-margin {
  margin-top: 20px;
}

.loading-spinner {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 50vh;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
}

.game-data-sources {
  margin-bottom: 2rem;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
  display: flex;
  align-items: center;
}

.refresh-button-container {
  margin: 1rem 0 2rem 0;
  text-align: center;
}

@media (max-width: 768px) {
  .navigation {
    margin-bottom: 20px;
  }
}
</style>