<template>
  <div class="game-page">
    <!-- Back to Home and Steam Button Row -->
    <div class="navigation-row">
      <Button @click="goBack" aria-label="Go back to home" size="small">
        ← Back to Search
      </Button>
      <UserProfile :user="user" />
    </div>

    <!-- Loading State -->
    <Spinner v-if="loading" message="Searching for game settings..." />

    <!-- Error State -->
    <ErrorMessage :message="error" @dismiss="clearError" class="error-with-top-margin" />

    <!-- Game Description Section -->
    <GameDescription :game="game" :loading="loading" />

    <!-- <GameSettings id="settings-section" :game="game" :user="user" :loading="loading" :error="error"
      :search-performed="searchPerformed" :processing-warning="processingWarning"
      @clear-processing-warning="clearProcessingWarning" @submit-vote="handleVoteSubmit" /> -->

    <AskAICard 
      v-if="game" 
      class="settings-section" 
      :title="`What is the community saying?`"
      :animate-text="true"
      :content="aiCardContent"
      :type-speed="15"
      :start-delay="800"
      @feedback="(feedback) => {
        submitGameSummaryVote(game.game_id, feedback)
      }"
    >
    </AskAICard>
        

    <!-- Game Reports Section -->
    <GameReportsSection v-if="game && game.reports" :reports="game.reports" />

    <GameDataSources class="game-data-sources" :game="game" />

    <!-- Processing game view -->
    <ProcessingWarning v-if="processingWarning" :game-name="gameTitle" @dismiss="clearProcessingWarning" />
    <div v-if="processingWarning" class="refresh-button-container">
      <RefreshButton :countdown-start="60" />
    </div>
    <RandomArt v-if="processingWarning" />
  </div>
</template>

<script>
import Button from '../components/base/Button.vue'
import Spinner from '../components/base/Spinner.vue'
import AskAICard from '../components/common/AskAICard.vue'
import ErrorMessage from '../components/common/ErrorMessage.vue'
import QuickLink from '../components/common/QuickLink.vue'
import RandomArt from '../components/common/RandomArt.vue'
import RefreshButton from '../components/common/RefreshButton.vue'
import GameDataSources from '../components/ui/GameDataSources.vue'
import GameDescription from '../components/ui/GameDescription.vue'
import GameReportsSection from '../components/ui/GameReportsSection.vue'
import GameSettings from '../components/ui/GameSettings.vue'
import ProcessingWarning from '../components/ui/ProcessingWarning.vue'
import ThumbsRating from '../components/ui/ThumbsRating.vue'
import UserProfile from '../components/ui/UserProfile.vue'
import apiService from '../services/backend/apiService.js'

export default {
  name: 'GamePage',
  components: {
    Button,
    QuickLink,
    GameSettings,
    GameDescription,
    GameReportsSection,
    ProcessingWarning,
    ErrorMessage,
    Spinner,
    GameDataSources,
    UserProfile,
    ThumbsRating,
    RefreshButton,
    RandomArt,
    AskAICard,
  },
  props: {
    gameId: {
      type: String,
      required: true,
    },
  },
  data() {
    return {
      game: null,
      loading: false,
      error: null,
      searchPerformed: false,
      processingWarning: false,
      user: null,
    }
  },
  computed: {
    gameTitle() {
      return this.game?.steam_app?.name || `Game ID ${this.gameId}`
    },
    aiCardContent() {
      if (!this.game?.game_performance_summary) return ''

      const summary = this.game.game_performance_summary
      const disclaimer =
        '\n\n<i>This is a brief summary of community feedback generated by AI and may contain errors.\nPlease refer to the community reports for accurate information.</i>'

      return summary + disclaimer
    },
  },
  async mounted() {
    // Add keyboard event listener for backspace key
    document.addEventListener('keydown', this.handleKeydown)
    this.updateDocumentTitle()
    this.loadGame()
    this.user = await apiService.fetchAuthUser()
  },
  unmounted() {
    // Remove keyboard event listener to prevent memory leaks
    document.removeEventListener('keydown', this.handleKeydown)
  },
  methods: {
    async handleVoteSubmit(gameSettingsId, type) {
      if (type === null) {
        await apiService.removeVote(gameSettingsId)
      } else {
        await apiService.submitVote(gameSettingsId, type)
      }
      // Refresh user and game data to reflect updated votes
      this.user = await apiService.fetchAuthUser()
      this.game = (await apiService.fetchGame(this.gameId)).game
    },
    handleKeydown(event) {
      // Check if backspace key is pressed and not in an input field
      if (event.key === 'Backspace' && !this.isInInputField(event.target)) {
        event.preventDefault()
        this.goBack()
      }
    },

    isInInputField(target) {
      // Check if the target element is an input field where backspace should work normally
      const inputTypes = ['INPUT', 'TEXTAREA', 'SELECT']
      return inputTypes.includes(target.tagName) || target.contentEditable === 'true'
    },

    goBack() {
      // Preserve the search term from the current URL when going back
      const urlParams = new URLSearchParams(window.location.search)
      const searchQuery = urlParams.get('q')

      if (searchQuery) {
        this.$router.push({ name: 'Home', query: { q: searchQuery } })
      } else {
        this.$router.push({ name: 'Home' })
      }
    },

    clearError() {
      this.error = null
    },

    clearProcessingWarning() {
      this.processingWarning = false
    },

    updateDocumentTitle() {
      document.title = `${this.gameTitle} - Steam Deck Settings DB`
    },

    async loadGame() {
      if (!this.gameId) {
        this.error = 'Unknown game ID.'
        return
      }

      this.loading = true
      this.error = null
      this.game = null
      this.searchPerformed = true
      this.processingWarning = false

      try {
        const res = await apiService.fetchGame(this.gameId)

        if (res.status === 'queued') {
          this.processingWarning = true
          return
        }

        const sortedReports = this.sortGameReportsPerRelevance(res.game.reports)
        this.game = { ...res.game, reports: sortedReports }
      } catch (err) {
        this.error = err.message
      } finally {
        this.loading = false
      }
    },

    sortGameReportsPerRelevance(reports) {
      // Example sorting logic: prioritize reports from certain sources
      const sourcePriority = {
        steamdeckhq: 1,
        sharedeck: 2,
        protondb: 3,
      }

      return reports.sort((a, b) => {
        const priorityA = sourcePriority[a.source] || 99
        const priorityB = sourcePriority[b.source] || 99
        return priorityA - priorityB
      })
    },

    submitGameSummaryVote(gameId, feedback) {
      const voteType = feedback === 'positive' ? 'up' : feedback === 'negative' ? 'down' : null
      if (!voteType) return
      return apiService.submitGameSummaryVote(gameId, voteType)
    },
  },
}
</script>

<style scoped>
.game-page {
  width: 100%;
}

.navigation {
  margin-bottom: 20px;
}

.settings-section {
  margin-top: 20px;
}

.error-with-top-margin {
  margin-top: 20px;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
}

/* Add flex row for navigation buttons */
.navigation-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1.5rem;
  margin-bottom: 2rem;
}

.game-data-sources {
  margin-bottom: 2rem;
}

.steam-login-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
  display: flex;
  align-items: center;
}

.refresh-button-container {
  margin: 1rem 0 2rem 0;
  text-align: center;
}

/* Show on mobile devices */
@media (min-width: 768px) {
  .quick-links-only-mobile {
    display: none;
  }
}
</style>